[package]
name = "pf"
description = "transfer file command line tool"
homepage = "https://github.com/robatipoor/pf"
keywords = ["paste", "file","transfer"]
license = "MIT"
repository = "https://github.com/robatipoor/pf"
version = "0.4.0"
authors = ["Mahdi <Mahdi.robatipoor@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = {version = "0.11.0",features = ["blocking"]}
url = "2.2.0"
clap = "2.33.3"
fern = "0.6.0"
chrono = "0.4.19"
log = "0.4.13"
dirs = "3.0.1"
failure = "0.1.8"

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "1.0.2"
