[package]
name = "pf"
description = "transfer file command line tool"
homepage = "https://github.com/robatipoor/pf"
keywords = ["paste", "file","transfer"]
license = "MIT"
repository = "https://github.com/robatipoor/pf"
version = "0.2.2"
authors = ["Mahdi <Mahdi.robatipoor@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.20"
url = "2.1.0"
clap = "2.33.0"
fern = "0.5.8"
chrono = "0.4.9"
log = "0.4.8"
dirs = "2.0.2"
failure = "0.1.5"

[dev-dependencies]
tempfile = "3.1.0"
assert_cmd = "0.11.1"
