[package]
name = "pf"
description = "transfer file command line tool"
homepage = "https://github.com/robatipoor/pf"
keywords = ["paste", "file","transfer"]
license = "MIT"
repository = "https://github.com/robatipoor/pf"
version = "0.2.1"
authors = ["Mahdi <Mahdi.robatipoor@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
url = "1.7.2"
clap = "2.33.0"
fern = "0.5.8"
chrono = "0.4.7"
log = "0.4.6"
dirs = "2.0.1"
failure = "0.1.5"

[dev-dependencies]
tempfile = "3.0.8"
assert_cmd = "0.11.1"
